### ISSUE TITLE
SPDY and HTTP/2

### ISSUE THREAD

**Issue by F21** [vulcand/vulcand#188]
We are building an application that will allow users to upload their own SSL certificates to serve their pages. We are planning to use vulcand to deal with our external requests as it currently provides the easiest way to manage certificates compared to HAProxy + confd.

It would be awesome if it could support SPDY (for legacy clients) and the newer HTTP/2.

**Comment by porjo** [comment]
+1

The Go [HTTP/2 Go package](https://github.com/bradfitz/http2) package [apparently supports the final spec now](https://www.reddit.com/r/golang/comments/2ym1h3/http2_server_that_can_run_lua_scripts_as_pages/cpfgk03).

**Comment by pires** [comment]
+1

**Comment by archisgore** [comment]
+1

**Comment by pierrebeaucamp** [comment]
Is anyone working on this? If not, I can probably implement the http2 package from bradfitz. Or do you all want to wait until his package is merged into Go's std library? 

Also, I think SPDY is worth its own issue, as it will be only used by legacy browsers which could also fall back on HTTP/1.x. Therefore, I don't believe that it's as important as HTTP/2 at the moment. Also, both protocols will need their own libraries anyways.

**Comment by pires** [comment]
I believe http2 is the way to go.

**Comment by brodock** [comment]
:+1: please enable it

**Comment by tboerger** [comment]
Feel free to open an pull request :)

**Comment by pierrebeaucamp** [comment]
Sorry for keeping you all waiting. Unfortunately, I haven't come up with an implementation yet. This is what I've found so far:

- As of https://github.com/bradfitz/http2/issues/59, the HTTP2 library will only work with TLS enabled.
- [Manners](https://github.com/mailgun/manners/) works fine with `http2.ConfigureServer(gracefulsrv.Server, nil)` and `ListenAndServeTLS()`.
- Simply putting `http2.ConfigureServer(srv.Server, nil)` in front of `srv.ListenAndServe()` won't work.

As far as I can tell, the whole tls config of Vulcand is done on the listener (I guess the *Vulcand* listener) and `http2.ConfigureServer()` basically configures the *net/http* listener. I have no idea where exactly the tls config is passed from Vulcand to Manners and then to net/http. 

Sorry again for all of you who waited for a PR, but I'm not actively working on this. If anyone has any ideas on how to proceed, please let me know.

**Comment by pires** [comment]
`vulcand` is tightly coupled with `oxy`, mailgun HTTP proxy implementation. I've made a redesign to allow for easily adding TCP and http2 proxying as well but the API doesn't feel quite there for me to provide a PR. Such as you @pierrebeaucamp, I'm no longer working on it actively.

**Comment by F21** [comment]
The http2 library has landed in go's experimental repo: https://godoc.org/golang.org/x/net/http2

**Comment by F21** [comment]
http2 has shipped with go 1.6 and is automatically enabled by default.

**Comment by archisgore** [comment]
It is indeed enabled by default.  I added it to the next proto list in this PR: https://github.com/vulcand/vulcand/pull/336

When that gets merged in, all TLS Listeners will offer http2 as a negotiation option.

**Comment by archisgore** [comment]
This still won't do e2e proxying of course - as in vulcan won't be able to take a server-pushed stream from a backend and push it all the way to the browser. But I'm working on that next.

**Comment by archisgore** [comment]
HTTP2 is now supported in vulcan. I'm going to close this. Passthrough should be a different feature and no proxy that I know of supports it.
