### ISSUE TITLE
`X-Forwarded-Proto: https` when Vulcand is handling HTTPS requests

### ISSUE THREAD

**Issue by rca** [vulcand/vulcand#192]
After adding a certificate to vulcand, I added an HTTPS listener with the following command:

```
vctl listener add --id example_https --host example.com --proto https --net tcp --addr '0.0.0.0:443' --trustForwardHeader
```

Is there an option or some other method of endusing `X-Forwarded-Proto` is set to `https` when vulcan is handling HTTPs?  Thanks!

**Comment by porjo** [comment]
Vulcand does this for me automatically, already!?

I've tested by running tcpdump on my backend server listening for incoming HTTP requests. I've then made an SSL request to vulcand, and I can see the following result:
```
GET / HTTP/1.1
Host: myhost.com
User-Agent: Go 1.1 package http
X-Forwarded-For: xxx.xxx.xxx.176
X-Forwarded-Host: myhost.com
X-Forwarded-Proto: https
X-Forwarded-Server: 
Accept-Encoding: gzip
```

What headers are you seeing when you test?

**Comment by BugRoger** [comment]
I actually do have the same problem. This is using an `https` listener but an backend with `http` servers. The frontends just have a `-route 'Host("myhost.com")'`.

```
GET /assets/empty-5ca34955e8f66b746191ebc097f3f86b.gif HTTP/1.1
Host: myhost.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
Referer: https://myhost.com
X-Forwarded-For: 10.0.0.1
X-Forwarded-Host: myhost.com
X-Forwarded-Proto: http
X-Forwarded-Server: 
```

**Comment by porjo** [comment]
Is it possible you are being double proxied? Try capturing the HTTP header for the request arriving at Vulcand for comparison?

**Comment by BugRoger** [comment]
I have a dedicated VM for my Vulcans and this is what I captured as outgoing traffic. I'll trace it again today.

**Comment by BugRoger** [comment]
I just rebuilt the whole scenario just using the simplest docker containers. It does work.

```
X-Forwarded-For: 192.168.59.3
X-Forwarded-Host: 192.168.59.104
X-Forwarded-Proto: https
X-Forwarded-Server:
```

I'm running Vulcan in front of Kubernetes. I guess, my assumption that the kube-proxy is just load balancing TCP connections is not true.

You can close this issue. It is working as expected.
