### ISSUE TITLE
Debug and resolve memory leak

### ISSUE THREAD

**Issue by tboerger** [vulcand/vulcand#216]
How can we debug and resolve some memory leak within vulcand? Even a vulcand instance without any traffic consumes multiple GB of memory after just a few days runtime.

**Comment by tboerger** [comment]
@psi-4ward do you have further informations?

**Comment by klizhentas** [comment]
@tboerger I was sucessfull before doing a dump of all goroutines periodically:

http://stackoverflow.com/questions/19094099/how-to-dump-goroutine-stacktraces

and looking at the memory profile to see what exactly is being leaked:

http://blog.golang.org/profiling-go-programs

**Comment by fracklen** [comment]
@klizhentas would it be an idea to add an endpoint to the admin api, where you could query the stacktrace for all goroutines? 
Since it's writing to a `Writer`, it would be quite trivial to return the dump over HTTP.

I'm guessing it would lower the barrier for identifying the culprit in a running production system, without the need for implementing periodic stack-dump, recompiling, deploying and waiting for it to build up memory usage.

**Comment by klizhentas** [comment]
That's a good idea! :+1:

**Comment by pquerna** [comment]
We just ran into a vulcand seemingly leaking a ton of sockets, would love to have this available in the admin API?

**Comment by pquerna** [comment]
Started profiling this, seems to be leaking Histogram instances. Looking deeper tonight.

**Comment by klizhentas** [comment]
I recall fixing one HDR histogram leak because these goroutines were working forever:

https://github.com/vulcand/vulcand/blob/master/proxy/mux.go#L119

**Comment by klizhentas** [comment]
the problem was: 

* etcd server was restarting
* new `mux` instance was created 
* goroutines for old `mux` instance never exited

not sure if this one is related though

**Comment by pquerna** [comment]
heap profile after running for 15 hours w/ minimal real traffic:

![out](https://cloud.githubusercontent.com/assets/110123/11846108/e523956a-a3cb-11e5-9026-e98cbdeaeb7c.png)

**Comment by pquerna** [comment]
dump of goroutines:

https://gist.github.com/pquerna/bd8319391690a9db7b22

As @klizhentas suggested, it appears there are 3 goroutines blocked on `mux.go:122`, which is holding the references to old generation mux instances, which is holding references to the Histograms:
https://github.com/vulcand/vulcand/blob/master/proxy/mux.go#L122

**Comment by pquerna** [comment]
Looking at the log line "stop emitting metrics", which includes the Mux ID thankfully, I see that in this period there were about 50 successful Stop()s called, and 2 Mux's that didn't get it called. Still looking.
