### ISSUE TITLE
X-Forwarded-Host gets mangled

### ISSUE THREAD

**Issue by fracklen** [vulcand/vulcand#221]
I have a setup, where I need a proxy in front of Vulcand. This proxy handles forward-headers, and rewrites the Host header before vulcand sees the request.

I would expect vulcand to leave the `X-Forwarded-*`-headers alone, if the `TrustForwardedHeader` option is enabled

I've made a pull-request in oxy https://github.com/mailgun/oxy/pull/19

**Comment by klizhentas** [comment]
merged. need to re-vendor it into vulcand though

**Comment by archisgore** [comment]
To original poster - I re-vendored the oxy library last week. Can you confirm you got what you need and close this issue?

**Comment by McSlow** [comment]
Merging introduces serious XSS issues if the backend trusts the content of X-Forward-For and displays it or puts it into some database:

Here a case where I add an X-Forward-For-Header in my client(!)
```
openssl s_connect --connect showmyip.domain.com:443
GET / HTTP/1.0
Host: showmyip.domain.com
X-Forwarded-For: <html><script>alert("Hello from the XSS Guys");</script></html>

HTTP/1.0 200 OK
Content-Length: 58
Content-Type: text/html; charset=utf-8
Date: Mon, 07 Nov 2016 11:54:33 GMT

<html><script>alert("Hello from the XSS Guys");</script></html>, 78.47.220.83closed 
```

Of course, an app should never trust any input parameter, but I guess there's a lot of out there in the wild...
