### ISSUE TITLE
vctl is mangling && in routes

### ISSUE THREAD

**Issue by iamruinous** [vulcand/vulcand#225]
```
/usr/bin/docker run --rm octoblu/vctl frontend upsert \
  --id my-service \
  --backend my-service-backend \
  --route "Host(\"$(/usr/bin/etcdctl get /some/key)\") && PathRegexp(\"/api/.*\")" \
  --trustForwardHeader \
  --vulcan http://$(/usr/bin/etcdctl get /vulcand/host):8182
```

```
etcdctl get /vulcand/frontends/octoblu-app-octoblu-api/frontend

{
  "Id":"my-service",
  "Route":"Host(\"example.com\") \u0026\u0026 PathRegexp(\"/api/.*\")",
  "Type":"http","BackendId":"my-service-backend",
  "Settings": { 
    "Limits": {"MaxMemBodyBytes":0,"MaxBodyBytes":0},
    "FailoverPredicate":"",
    "Hostname":"",
    "TrustForwardHeader":true
  }
}
```

**Comment by tboerger** [comment]
That's not vctl, that's a bash thing. So IMHO invalid issue.

**Comment by royvandewater** [comment]
It looks like the && are inside quotes, so bash should just pass them in as ampersand literals to vctl.

@tboerger How would you propose setting a --route through bash that contains two conditions and'ed together?

**Comment by tboerger** [comment]
I never used variables in that context, so I'm able to use single quotes, that always works. And btw the documention mentions single quotes only as well like https://vulcand.io/proxy.html#frontends for the ```-route```parameter at the first example.

**Comment by royvandewater** [comment]
I just tried this: 

curl -X POST -H "Content-Type: application/json" http://172.17.8.101:8182/v2/frontends      -d '{"Frontend": {"Id":"f1", "Type": "http", "BackendId": "some-backend", "Route": "Path(\"/\") && Host(\"my-host.com\")"}}'

and got this as the response from curl, corroborated by etcd:

{"Id":"f1","Route":"Path(\"/\") \u0026\u0026 Host(\"my-host.com\")","Type":"http","BackendId":"some-backend","Settings":{"Limits":{"MaxMemBodyBytes":0,"MaxBodyBytes":0},"FailoverPredicate":"","Hostname":"","TrustForwardHeader":false}}

**Comment by tboerger** [comment]
Yeah, wrong escaping ;)

**Comment by royvandewater** [comment]
Do you mean that bash is escaping the ampersands incorrectly? 

I tried to take bash out of the equation by using Postman, but I get the same results
<img width="936" alt="screenshot 2015-07-22 15 04 51" src="https://cloud.githubusercontent.com/assets/72016/8838665/2a079fd0-3083-11e5-8895-4bdb0440fd70.png">

**Comment by royvandewater** [comment]
I created some backends and tried it. Even though the ampersands are all escaped, it still enforces the route exactly as it should. Its only a cosmetic problem, but it certainly sent us on a wild goose chase :-)

Go defines this behavior explicitly here: http://golang.org/pkg/encoding/json/#Marshal

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. The angle brackets "<" and ">" are escaped to "\u003c" and "\u003e" to keep some browsers from misinterpreting JSON output as HTML. Ampersand "&" is also escaped to "\u0026" for the same reason.

I guess it'd be nice to see non-escaped ampersands, but no biggy

**Comment by tboerger** [comment]
Ok, i found some kind of issue. If i try to execute that with docker exec directly i loose everything starting at ```&&```, if i get into the container with ```docker exec -ti vulcand bash``` and execute something with ```&&``` it simply works. So there seems to be something getting lost within ```docker exec```.

**Comment by AlexisMontagne** [comment]
@archisgore you can close this issue, could you also release a new version (github release + docker image)?

**Comment by archisgore** [comment]
Closed the issue. I'll let someone from mailgun handle the github release + docker image. I haven't done it before and don't have the bandwidth unfortunately.
