### ISSUE TITLE
Build the minimal image

### ISSUE THREAD

**Issue by mindnuts** [vulcand/vulcand#248]
I think it would be good if you can document the steps to build a minimal image for use with Docker. The image on Docker hub seems to be ~550MB.

S

**Comment by tboerger** [comment]
What about webhippie/vulcand? :)

**Comment by mindnuts** [comment]
@tboerger  No offence but Trusted build from mailgun would be preferred by more people. Also if you can build a static binary you can use tricks from the link below to reduce your image size further.

https://github.com/jamiemccrindle/dockerception

**Comment by tboerger** [comment]
Whatever you prefer, 102MB container size including tools like logstash-forwarder is already not bad. My 35.600 downloads are trusted enough from my side :D

**Comment by freexmonster** [comment]
size 50MB psitrax/vulcand (system  AlpineLinux)  and "run /usr/bin/vulcand -apiInterface=0.0.0.0 -interface=0.0.0.0 -etcd=http://"you-ip":4001 -port=80 -apiPort=8182"

**Comment by mindnuts** [comment]
ended up creating my image from Alpine and static build of the application.
