### ISSUE TITLE
Question: how to setup multiple SSL hosts with one vulcand instance

### ISSUE THREAD

**Issue by mindnuts** [vulcand/vulcand#252]
Hi, i would like to use vulcand to serve SSL traffic for two separate hosts.

Assuming that Vulcand is listening on 80 and 443 port i configure two certificates like so:

```
etcdctl set /vulcand/hosts/blah.co.uk/host '{"Settings": {"KeyPair": "something"}}'
etcdctl set /vulcand/hosts/blahblah.com/host '{"Settings": {"KeyPair": "something"}}'
```

I have already setup two listeners like so:

```
curl --silent -L http://${ETCD_HOST}:4001/v2/keys/vulcand/listeners/http -XPUT -d value='{"Protocol":"http", "Address":{"Network":"tcp", "Address":"0.0.0.0:80"}}'
curl --silent -L http://${ETCD_HOST}:4001/v2/keys/vulcand/listeners/https -XPUT -d value='{"Protocol":"https", "Address":{"Network":"tcp", "Address":"0.0.0.0:443"}}'
```

Vulcand is started with the seal key i used to seal the two keypairs. The issue i am facing is that vulcand serves the same certificate for both the hosts. Am i doing anything wrong here? Please help.

**Comment by klizhentas** [comment]
Vulcand uses SNI to match cert to the hostname, how do you test your setup?

**Comment by mindnuts** [comment]
@klizhentas At the moment i am using self signed wildcard certificates and using local ip to resolve the domain names. In the browser the certificate presented  is always the last certificate setup.

example: 
 * setup foo.com visit foo.com in browser and browser only complains about self signed certificate
 * setup foobar.com, visit foobar.com in browser and browser complains about self signed certificate.
 * refresh foo.com in browser and browser says host mismatch as its issued for foobar.com

Please let me know if this is not enough information.

**Comment by horkhe** [comment]
Closing as outdated. Please reopen if you still interested.
