### ISSUE TITLE
Consider stop vendoring

### ISSUE THREAD

**Issue by pquerna** [vulcand/vulcand#253]
I believe vulcand should not be vendoring.  It is not a 'classic' program, but still a series of libraries that you compile and add your own features to.

Several issues in the last few months have been caused by vendoring dependencies, people unknowingly breaking APIs, not keeping dependencies up to date for fixed bugs, etc.

Additionally, user's of Vulcan who use `vbundle` or otherwise add custom middlewares will do their own vendoring of dependencies.  But because you depend directly upon vulcand/\* packages, which use Godep'ed dependencies, you must also use Godep in your bundling.

For example, we were considering switching to  https://github.com/kardianos/govendor/ for most of our projects, because of issues like `+windows` build flags not being understood by Godeps.  But because vulcand uses Godeps, we can't have get to a consistent flattening of dependencies.

**Comment by tboerger** [comment]
Vendoring is totally reasonable to take care about a working state. I would just suggest to build only on golang 1.5 and to use the new vendoring method with for example glide for managing the deps.

**Comment by pquerna** [comment]
Right, if we are going to keep vendoring, at least use the 1.5-experiment method, with whatever tooling you want for managing that.

**Comment by pquerna** [comment]
PR #254 goes to direct dependencies, nothing vendored.

This would be my preference for the next 3-6 months, until go 1.6 is out and then re-consider using the native vendoring, assuming it becomes less experiemtnal

**Comment by horkhe** [comment]
Looks like vendoring is here to stay especially taking in account [this saga](https://blog.gopheracademy.com/advent-2016/saga-go-dependency-management/). Let's wait for the final decision to be made and `go tool dep` to appear in the SDK and then migrate to it. I am closing this for now. @pquerna, please reopen if you disagree.
