### ISSUE TITLE
Allow vulcand to expose in-progress connections (for instance draining.)

### ISSUE THREAD

**Issue by archisgore** [vulcand/vulcand#256]
As vulcand grows, I presume Websockets, and long-living connections will become a key scenario/use-case.

We know that when we remove servers from a backend or remove a backend entirely, vulcand will allow any connections to that server to drain before releasing it.

However, for long-lived connections, it may be necessary for administrators to know any such pending connections before they take the server itself out of commission. This isn't a scenario we've hit yet, but two years down the line I imagine it'll come up.

I'm happy to contribute code to help with this - if we can land a design.

I'm imagining some sort of status API that allows vctl to query current on-going connections, or perhaps an etcd key that stores in-progress connections. Sadly this cannot be done in middlewares since the server is selected after all middlewares are done processing - so they have no visibility into what physical endpoint the connection will go to.

Using this feature, we should be able to script the provisioning and decommissioning of any backend instances safely.

**Comment by klizhentas** [comment]
@archisgore to speed up development, here's what I'm planning to do: 

* Vulcand and associated projects (oxy, predicate, route) will be moved to separate org
* @archisgore and @pquerna will be given committers rights alongside mailgunners and me(I'm no longer at Mailgun)

@r0mant let me know when you plan to do this

**Comment by r0mant** [comment]
I'll do it tonight/tomorrow if no pressing issues come up.

**Comment by archisgore** [comment]
Thanks for doing this romant. I promise to be a good actor here. I'm beginning to merge some PRs and also will ask some PR submitters to resubmit - those who broke the UTs due to that old race condition.

Watch out for path-updates coming soon (all packages refer to github.com/mailgun/... and I'll make those updates in order of dependencies first.
