### ISSUE TITLE
Create gitter chat

### ISSUE THREAD

**Issue by tboerger** [vulcand/vulcand#258]
To get a better platform for discussion or to get help how to configure things I would suggest to create a gitter chat for vulcand/vulcand. Forums/Mailinglists like the google group are pretty dead.

**Comment by JonGretar** [comment]
+1

**Comment by freexmonster** [comment]
I agree with your message. It is very important!!! At the moment I have a lot of ideas and questions, and would like to discuss them. Manual from the official website is not enough.

**Comment by tboerger** [comment]
I will close that because of lacking interest :(
