### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by ekozan** [vulcand/vulcand#260]
Hi, 

I want to speak about the possibility of implement an auto configurator ( ex: for kubernetes or mesos ) 
I think the best way is to implement firstly the leader election ( ttl based with key/value backend ? ) 
After define on standard for the configurator 

Any plan for implement this ? 
Can I propose some PR ?

**Comment by klizhentas** [comment]
@ekozan we've just been talking about this recently - some folks from CoreOS added integration steps for k8s as a hack project, I want to take a look at that and merge some of it upstream - the idea is implement k8s native backend that uses k8s API instead of using etcd directly

**Comment by ekozan** [comment]
ho yeah and use the labels like https://github.com/Nordstrom/kubernetes-vulcand-router for the config

**Comment by klizhentas** [comment]
yeah, the plan is to have a deep integration with k8s

**Comment by ekozan** [comment]
how do you plan to handle many requests I think the api can't handle this ? cache in memory ?

**Comment by zoidbergwill** [comment]
The [kubernetes vulcand router](https://github.com/Nordstrom/kubernetes-vulcand-router) has been deprecated in favour of [romulus](https://github.com/timelinelabs/romulus/)

**Comment by ekozan** [comment]
now we have to use ingress

**Comment by tboerger** [comment]
romulus just registers on vulcand, so just one piece changed :)
