### ISSUE TITLE
Blog domain has expired

### ISSUE THREAD

**Issue by bryce-gibson** [vulcand/vulcand#265]
It looks like blog.vulcanproxy.com has expired?

I'm not sure if you'd like to renew it, or remove it from the readme?

Just thought you might like to know :-)

**Comment by christian-blades-cb** [comment]
:+1: Just embarrassed myself by telling a colleague to RTFM and handed him a dead link.

**Comment by tboerger** [comment]
The blog is not a manual :)

**Comment by christian-blades-cb** [comment]
@tboerger Look, I don't tell you how to embarrass yourself.

**Comment by klizhentas** [comment]
hey everyone, thanks for the note. I still need to port blog and docs to some external domain will take care of it

**Comment by horkhe** [comment]
There is no blog anymore.
