### ISSUE TITLE
Support Versioning

### ISSUE THREAD

**Issue by alexkappa** [vulcand/vulcand#271]
Hello,

Would it make sense to add support for versioning to vulcan as done in the [heroku](https://devcenter.heroku.com/articles/platform-api-quickstart) or [github](https://developer.github.com/v3/#current-version) api's? I imagine it having the frontend parse a `Accept` header and vulcan would then route to a specific server from the configured backend. Servers would be registered with an additional `-version` flag.

For example:

```
$ vctl backend upsert -id b1

$ vctl server upsert -b b1 -id srv1 -url http://localhost:5000 -version 1.0.0
$ vctl server upsert -b b1 -id srv2 -url http://localhost:5001 -version 2.0.0

$ vctl frontend upsert -id f1 -b b1 -route 'Path("/")'

$ curl -H 'Accept: application/vnd.vulcan+json; version=1' http://example.com
> Hit srv1.
$ curl -H 'Accept: application/vnd.vulcan+json; version=1.0.*' http://example.com
> Hit srv1.
$ curl -H 'Accept: application/vnd.vulcan+json; version=2' http://example.com 
> Hit srv2.
$ curl -H 'Accept: application/vnd.vulcan+json; version=latest' http://example.com
> Hit srv2.
```

I would gladly work on this, hopefully with some guidance. Feedback is greatly appreciated!

Thanks!

**Comment by archisgore** [comment]
As it happens, this scenario is specifically what like vulcan is designed for already. You can do it by registering a different frontend, and the route would match your vulcan header. You can then attach that version's backend and servers to it.

**Comment by alexkappa** [comment]
Right, I haven't considered that approach. Thanks a lot!
