### ISSUE TITLE
Domain vulcand.io has expired and pending delete

### ISSUE THREAD

**Issue by designgrill** [vulcand/vulcand#274]
$ whois vulcand.io

Domain : vulcand.io
Status : pendingDelete
Expiry : 2015-12-27
Delete : 2016-03-27 00:30

**Comment by tapank** [comment]
+1

**Comment by shrinathaithal** [comment]
+1

**Comment by dannykopping** [comment]
...and the site is now down

**Comment by vmattos** [comment]
Yep. It's down

**Comment by rbucker** [comment]
vulcandproxy.com too except now a squatter has that one,

**Comment by freexmonster** [comment]
+1

**Comment by klizhentas** [comment]
hey, sorry I was on vacation and it slipped through the cracks. I will try to recover vulcand.io or register another one and point the website to it. Thanks!

**Comment by klizhentas** [comment]
I've quickly deployed docs mirror to http://vulcand.github.io/ and will remap the vulcand.io once I recover it, thanks everyone. Also, please note that, this is a side project for all of us, so please be patient :)

**Comment by shrinathaithal** [comment]
Great...
Thank you Alexander...

**Comment by vmattos** [comment]
We appreciate the workaround! :)
:+1:
