### ISSUE TITLE
Blasphemous Question: Why not use Traefik?

### ISSUE THREAD

**Issue by vanthome** [vulcand/vulcand#289]
I've recently moved from vulcand to [https://docs.traefik.io/](Traefik) becuase I wanted HTTP 2.0 support as multiple config backend support. I have to say from my perspective Traefik provides all Vulcand features that I overlook plus much more.
So I want to ask the blasphemous, why not move to Traefik / join forces with them?

**Comment by mindnuts** [comment]
:+1: 

It supports Let's encrypt natively and seems to be maintained more.

**Comment by klizhentas** [comment]
hey folks, it's open source, so if you like Traefik use it. I've created Vulcand to solve and research particular problem - resiliency in micro-service architecture, I have no intent on turning it into generic proxy with support for everything. So use the tool that works better for you.
