### ISSUE TITLE
"Route":"Path(`/.*`)" doesn't work

### ISSUE THREAD

**Issue by erolg** [vulcand/vulcand#293]
Here is my frontend, 

I want to acess / and /smth/10/smth etc. But this path doesn't work.

```
{
	"Id": "fdemo_blog_1",
	"Route": "Path(`/.*`)",
	"Type": "http",
	"BackendId": "bdemo_blog_1",
	"Settings": {
		"Limits": {
			"MaxMemBodyBytes": 0,
			"MaxBodyBytes": 0
		},
		"FailoverPredicate": "",
		"Hostname": "",
		"TrustForwardHeader": false
	}
}
```

**Comment by nvartolomei** [comment]
Use `PathRegexp` instead of `Path`.

**Comment by horkhe** [comment]
Exactly `Path` in fact means [Trie](https://en.wikipedia.org/wiki/Trie) based path where every item between two adjucent `/` is a trie node. Use `PathRegex` as @nvartolomei suggested if you want a regex based route. But I would recommend using Trie based routes if you plan to have many frontends, for it is way more performant.
