### ISSUE TITLE
Got Empty body when Rewrite Request don't match the regex

### ISSUE THREAD

**Issue by bernardoVale** [vulcand/vulcand#320]
Traefik uses vulcand to redirect requests based on a regex.

We've detected a bug when the request doesn't match the regex. We got a 200 Status Code but when you look at the body there's not content.

[traefik issue](https://github.com/containous/traefik/issues/679)

I've written the following test case [here](https://github.com/vulcand/vulcand/blob/master/plugin/rewrite/rewrite_test.go) that confirmed that the request body is empty:

```
//The object of this test is to ensure that if the rewrite doesn't match the regex
// the request will be forward with the same content
func (s *RewriteSuite) TestRewriteNoMatchBody(c *C){
	var outURL string
	expectedBody := []byte("Expected Body Content")

	handler := http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		outURL = rawURL(req)
		w.Write(expectedBody)
	})

	rh, err := newRewriteHandler(handler, &Rewrite{"^http://localhost/foo/(.*)", "http://localhost$1", false, false})
	c.Assert(rh, NotNil)
	c.Assert(err, IsNil)

	srv := httptest.NewServer(rh)
	defer srv.Close()

	re, _, err := testutils.Get(srv.URL+"/fooo/bar", testutils.Host("localhost"))
	c.Assert(err, IsNil)
	c.Assert(re.StatusCode, Equals, http.StatusOK)
	c.Assert(outURL, Equals, "http://localhost/fooo/bar")

	body, err := ioutil.ReadAll(re.Body)
	c.Assert(string(body), Equals, string(expectedBody))
	c.Assert(err, IsNil)
}
```

Got error:
```
c.Assert(string(body), Equals, string(expectedBody))
Expected :string = "Expected Body Content"
Actual   :string = ""
```

I'm still investigating this problem, but I wanted to fill an issue first just to make sure this is really a bug or if this is intended.

**Comment by codymwalker** [comment]
@bernardoVale Did anything ever come of this? I'm running into the same issues you referenced in https://github.com/containous/traefik/issues/679 when non regex matches return an empty 200.

**Comment by bernardoVale** [comment]
@codymwalker , I've debugged this for a few days. I realize that the problem is not on vulcand. that's why I've closed this issue here.

**Comment by bernardoVale** [comment]
Still don't know where the problem is =/
