### ISSUE TITLE
Does it support persistent connections?

### ISSUE THREAD

**Issue by muellermichel** [vulcand/vulcand#327]
Let's say I have a cluster of database replicas that I would like to make available under a frontend. These databases replicate with each other. Can I have VulcanD serve the same backend to the same client ID if possible, such that the UI can be made consistent even when the DBs are still replicating the newest state?

**Comment by horkhe** [comment]
The short answer is no. The long answer is as follows: Vulcand is L7 HTTP proxy, it does not proxy arbitrary TCP traffic. Even though it is possible to configure both inbound and outbound connections with infinite timeouts, the proxy decisions are made on per request basis, so different requests coming from the same inbound connection can be proxied to different outbound connections.
