### ISSUE TITLE
How to make the config persistent?

### ISSUE THREAD

**Issue by ikandars** [vulcand/vulcand#332]
Is it possible? or I should backup to a json file every time I add new configuration?

**Comment by horkhe** [comment]
@ikandaras what configuration are you talking about? Could you please be more specific.

**Comment by gchaincl** [comment]
@ikandars are you running etcd inside a container?

**Comment by ikandars** [comment]
Hi, sorry for my late response. @horkhe I mean is frontend, backend and host configuration. Since it can add on the fly, I thought it will disappear every time I restart the service. But @gchaincl give me a clue that its more about docker things, not vulcand it self. This is valid since I'm not use docker persistent volume.

thx all
