### ISSUE TITLE
vulcand exits when etcd watch fails

### ISSUE THREAD

**Issue by mischief** [vulcand/vulcand#55]
https://github.com/mailgun/vulcand/blob/master/backend/etcdbackend/etcdbackend.go#L399

results in the following on my coreos cluster:
Aug 04 02:17:25 coreos.novalocal bash[6109]: ERROR Aug  4 02:17:25.192: [etcdbackend.go:405] Stop watching: Etcd client error: unexpected end of JSON input
Aug 04 02:17:25 coreos.novalocal bash[6109]: INFO  Aug  4 02:17:25.192: [service.go:121] Stopped watching changes with error: unexpected end of JSON input. Shutting down 
with error
Aug 04 02:17:25 coreos.novalocal bash[6109]: INFO  Aug  4 02:17:25.192: [service.go:111] Got request to shutdown with error: unexpected end of JSON input
Aug 04 02:17:25 coreos.novalocal bash[6109]: Service exited with error: Service exited with error: unexpected end of JSON input

i was told in coreos irc that the watch should be retried and not treated as a fatal error.

perhaps vulcand can catch json.SyntaxError (the type of the error passed) and not treat it as fatal, or ignore any error.

**Comment by pshabalin** [comment]
Etcd 2.0 should not respond with empty body
https://github.com/coreos/go-etcd/issues/170#issuecomment-68959994
