### ISSUE TITLE
Add alternative backends

### ISSUE THREAD

**Issue by thedrow** [vulcand/vulcand#9]
- [x] The backends API should be highly documented.
- [x] Any reference to Etcd from the Backend type must be removed. (Related issues: #5)
- [x] Create a toturial explaining how to write a backend.
- [ ] Create a Consul backend.
- [ ] Create a Consul DNS backend.
- [ ] Create a SkyDNS2 backend.
- [ ] Create a ZooKeeper backend.

**Comment by slantview** [comment]
Where is this at? We use a custom service discovery that is based on [Eureka](https://github.com/Netflix/eureka). I'm writing a custom engine, but the service package still explicitly uses etcdng. If you can outline how you would like this to look from a design perspective of loading engines, I'd be willing to help out.

**Comment by klizhentas** [comment]
@slantview 

Steve, after thinking some time about your question, I would take the same approach as with middlewares:

https://docs.vulcand.io/middlewares.html

I will spend some time in the next several days to roll out the support in `bundle` and will write an example article for you.

Thanks,
Sasha

**Comment by slantview** [comment]
Oh wow, thanks for the fast response. What do you think about run-time? I was thinking that changing the flags from -etcd* to -engine and -engineOptions would be good, then we could standardize the stuff passed to engine.New and let each engine parse the configs passed in, or potentially offer a config item with a standardized map of options passed to engineOptions with a key:value set.

Thoughts?

**Comment by klizhentas** [comment]
I was thinking about using the same pattern as for middlewares:

https://github.com/mailgun/vulcand-auth/blob/master/auth/auth.go#L86

Basically each engine plugin will define a set of command line flags that would make sense for it, so a compiled version of vulcand will accept the right parameters with validation.

**Comment by slantview** [comment]
I'll spend some time looking at it this weekend, that sounds cool. I haven't played with middlewares yet, but that sounds legit.

Also would love to chat privately about what scale you run this at. If you don't mind, I'd love to hit you up on email to discuss. 

We run a very large worldwide game, and I'm looking at using this for some stuff, but our scale usually crushes software. :P

Either hit me up srude@riotgames.com or I'll email you next week.

Also go grab a drink, it's too late to be replying to me on github issues on a Friday ;)

**Comment by klizhentas** [comment]
Sure, would like to know better about the scale and request distribution, can definitely share some expectations about it's performance under various conditions.

Just email me next week: sasha.klizhentas@mailgunhq.com

**Comment by sebest** [comment]
Hello,

Any update on a consul backend?

**Comment by sandstrom** [comment]
We're using consul, just chiming in to say a consul backend would be awesome! :fireworks:

**Comment by x0e-foobar** [comment]
Consul support for vulcand would be great! :+1:

**Comment by Cad** [comment]
+1 consul

**Comment by thedrow** [comment]
https://github.com/docker/libkv looks promising and might help us provide Consul and Zookeeper support.
We just need volunteers for this.

**Comment by tboerger** [comment]
I understand that some people want to have support for consul or zookeeper. But where should it help to integrate skydns into vulcand? For me vulcand and skydns are totally different things.

**Comment by benley** [comment]
I don't see why there needs to be anything specific to SkyDNS, but a generic DNS-based discovery mechanism could be useful. The implementation could query DNS for SRV records; people might find it useful with SkyDNS, Mesos-DNS, and probably a variety of in-house setups.

Prometheus has just such a thing already written in Go for reference: https://github.com/prometheus/prometheus/blob/master/retrieval/discovery/dns.go

For that matter, they've got zookeeper and consul discovery there too:
https://github.com/prometheus/prometheus/blob/master/retrieval/discovery/serverset.go
https://github.com/prometheus/prometheus/blob/master/retrieval/discovery/consul.go

**Comment by benoist** [comment]
+1 for consul

**Comment by sandstrom** [comment]
@klizhentas I'm super-eager to use vulcand, but we're on Consul. Any chance that [libkv](https://github.com/docker/libkv) (or something else) could make vulcan work with consul?

**Comment by klizhentas** [comment]
libkv looks super-promising indeed, I would totally accept the PR migrating the backends to libkv

**Comment by sandstrom** [comment]
Good to hear! Unfortunately I've never written a single line of Go (and very long work weeks eat all my time). But I'll pray that some one else might. :pray:

**Comment by wienczny** [comment]
[libkv](https://github.com/docker/libkv) just supports [consul](https://github.com/hashicorp/consul)'s /kv namespace. So you can't access /catalog. Using /catalog/services you can get access to the nodes currently providing a given service. This what I would expect vulcand to use :wink:
I do like [consul](https://github.com/hashicorp/consul) but without access to these, [consul](https://github.com/hashicorp/consul) loses some advantage.
@klizhentas Do you think this would be a problem?

**Comment by klizhentas** [comment]
tbh I'm not familiar with consul, I just know that it would be possible to release a consul-compatible backend, may be via adding more logic to libkv or writing a new native client to it.

**Comment by miracle2k** [comment]
I'm running consul-template in a separate docker container to have it copy the catalog data to vulcand/etcd. Maybe it's useful for some:

https://github.com/miracle2k/consul2vulcan

**Comment by armon** [comment]
Just wanted to mention that the Go API client for Consul is complete, and should support everything needed. (http://godoc.org/github.com/hashicorp/consul/api). At any rate, the Consul features are a superset of etcd so it should be possible to have at least equal compatibility.

**Comment by tboerger** [comment]
@armon we know the client, there was just a discussion about a generic client that covers directly etcd and consul, instead of adding different implementations...

**Comment by wienczny** [comment]
How about extending libkv to emulate namespaces in each call? This could be done by adding a mapping function to the store configuration. In etcd this could be KV -> /, CATALOG -> /catalog or any user defined function. This way you could access values from etcd like they were stored in consul.

This would result in something like:

    kv.putNS(libkv.CATALOG, "somekey", "somevalue")
    kv.getNS(libkv.KV, "somekey") == nil
    kv.getNS(libkv.CATALOG, "somekey") == "somevalue"

    func map(int keyspace, key string) {
        if  keyspace == libkv.CATALOG && key == "service/redis/" {
            return "/catalog" + "/service/redis"
        }
        return key
    }

On the other side you could even use the mapping-function to access consul's data like it was in etcd:

    func map(int keyspace, key string) string {
        if  key == "catalog/service/redis/" {
            return "another/path"
        }
        return key
    }

Additionally there might be another function mapping the result from a store.

@armon Do you think this way at least a readonly view of consuls data can be represented?
@klizhentas Would this be usable?

**Comment by armon** [comment]
Certainly possible. I don't know the code base to recommend the cleanest approach. You could wrap the consul client to do this KV simulation fairly easily however.

**Comment by cusspvz** [comment]
+1 for consul

**Comment by sielaq** [comment]
+1
but I think vulcand is little bit behind comparing to traefik,
traefik supports much more backends (including consul).
http://traefik.github.io

**Comment by SamuelMarks** [comment]
Wow, Traefik looks awesome

**Comment by cusspvz** [comment]
Didn't knew about Traefik either!

**Comment by sandstrom** [comment]
@sielaq Great suggestion, thanks!

**Comment by tboerger** [comment]
Traefik looks nice but it's not distributed except for etcd and you have to run an instance for every listening port :(

**Comment by sielaq** [comment]
@tboerger, etcd is not the only distributed backend. Moreover if you use distributed backend as your primary data for configuration like consul, mesos/marathon, etcd, etc. then you don't need to have distributed proxy, since every instance got its data fully agnostic. And why running multiple ports while you can use only one port 80 and hostname (DNS) to discover your service (consul / etcd+skydns, etc..)

**Comment by tboerger** [comment]
Look at vulcand, listen to as many ports as you want, do redirects from 80 to 443, all in a single instance... I thought about the docker integration of vulcand to get rid of an registrator.

**Comment by sielaq** [comment]
For those who just need small HTTP router (LB) for Consul,
our colleagues have just released https://github.com/eBay/Fabio
enjoy

**Comment by teodor-pripoae** [comment]
Hi,

Additional backends can be implemented by using [libkv](https://github.com/docker/libkv). This creates an abstraction over etcd/consul/zookeeper and I think it implements all the features required by vulcand.

**Comment by cusspvz** [comment]
I would like to be a little bit more ambitious and ask you to include Rancher's metadata service so `vulcand` can act like an alternative of their current LB.

**Comment by wmangano** [comment]
+1 consul

**Comment by soupdiver** [comment]
Is there any update on the Consul integration? Are there any show stoppers or does just someone have to implement it?

**Comment by horkhe** [comment]
Closing as mentioning to many things. Each of them should be an isolated issue.
